/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    BacktestList: typeof import('./src/components/dashboard/BacktestList.vue')['default']
    DecayAlert: typeof import('./src/components/dashboard/DecayAlert.vue')['default']
    ElAlert: typeof import('element-plus/es/components/alert/index')['ElAlert']
    ElAutoResizer: typeof import('element-plus/es/components/table-v2/index')['ElAutoResizer']
    ElButton: typeof import('element-plus/es/components/button/index')['ElButton']
    ElButtonGroup: typeof import('element-plus/es/components/button/index')['ElButtonGroup']
    ElCard: typeof import('element-plus/es/components/card/index')['ElCard']
    ElCheckbox: typeof import('element-plus/es/components/checkbox/index')['ElCheckbox']
    ElCheckboxButton: typeof import('element-plus/es/components/checkbox/index')['ElCheckboxButton']
    ElCheckboxGroup: typeof import('element-plus/es/components/checkbox/index')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es/components/col/index')['ElCol']
    ElDatePicker: typeof import('element-plus/es/components/date-picker/index')['ElDatePicker']
    ElDialog: typeof import('element-plus/es/components/dialog/index')['ElDialog']
    ElEmpty: typeof import('element-plus/es/components/empty/index')['ElEmpty']
    ElForm: typeof import('element-plus/es/components/form/index')['ElForm']
    ElFormItem: typeof import('element-plus/es/components/form/index')['ElFormItem']
    ElIcon: typeof import('element-plus/es/components/icon/index')['ElIcon']
    ElInput: typeof import('element-plus/es/components/input/index')['ElInput']
    ElInputNumber: typeof import('element-plus/es/components/input-number/index')['ElInputNumber']
    ElOption: typeof import('element-plus/es/components/select/index')['ElOption']
    ElOptionGroup: typeof import('element-plus/es/components/select/index')['ElOptionGroup']
    ElPagination: typeof import('element-plus/es/components/pagination/index')['ElPagination']
    ElProgress: typeof import('element-plus/es/components/progress/index')['ElProgress']
    ElRadio: typeof import('element-plus/es/components/radio/index')['ElRadio']
    ElRadioButton: typeof import('element-plus/es/components/radio/index')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es/components/radio/index')['ElRadioGroup']
    ElResult: typeof import('element-plus/es/components/result/index')['ElResult']
    ElRow: typeof import('element-plus/es/components/row/index')['ElRow']
    ElSelect: typeof import('element-plus/es/components/select/index')['ElSelect']
    ElSkeleton: typeof import('element-plus/es/components/skeleton/index')['ElSkeleton']
    ElSlider: typeof import('element-plus/es/components/slider/index')['ElSlider']
    ElSwitch: typeof import('element-plus/es/components/switch/index')['ElSwitch']
    ElTable: typeof import('element-plus/es/components/table/index')['ElTable']
    ElTableColumn: typeof import('element-plus/es/components/table/index')['ElTableColumn']
    ElTableV2: typeof import('element-plus/es/components/table-v2/index')['ElTableV2']
    ElTag: typeof import('element-plus/es/components/tag/index')['ElTag']
    ErrorBoundary: typeof import('./src/components/ErrorBoundary.vue')['default']
    FactorStats: typeof import('./src/components/dashboard/FactorStats.vue')['default']
    Guide: typeof import('./src/components/common/Guide.vue')['default']
    KLineChart: typeof import('./src/components/dashboard/KLineChart.vue')['default']
    KpiCards: typeof import('./src/components/dashboard/KpiCards.vue')['default']
    MarketOverview: typeof import('./src/components/dashboard/MarketOverview.vue')['default']
    MiningTasks: typeof import('./src/components/dashboard/MiningTasks.vue')['default']
    MobileTabBar: typeof import('./src/components/layout/MobileTabBar.vue')['default']
    PageContainer: typeof import('./src/components/common/PageContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionCard: typeof import('./src/components/common/SectionCard.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    SkeletonLoader: typeof import('./src/components/SkeletonLoader.vue')['default']
    TopBar: typeof import('./src/components/layout/TopBar.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es/components/loading/index')['ElLoadingDirective']
  }
}
